CREATE TABLE products (
    id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
    sku VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    price INT(10) NOT NULL,
    productType ENUM ('DVD','Book','Furniture') NOT NULL,
    CONSTRAINT PRIMARY KEY(id)
);


CREATE TABLE dvd (
    id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
    product_id INT(6) UNSIGNED NOT NULL,
    size INT(10) NOT NULL,
    
    CONSTRAINT PRIMARY KEY(id),
    CONSTRAINT FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
    );


CREATE TABLE book (
    id INT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
    product_id INT(6) UNSIGNED NOT NULL,
    weight INT(10) NOT NULL,
    
    CONSTRAINT PRIMARY KEY(id),
    CONSTRAINT FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
    );


CREATE TABLE furniture (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    height INT(10) NOT NULL,
    width INT(10) NOT NULL,
    length INT(10) NOT NULL,
    
    CONSTRAINT PRIMARY KEY(id),
    CONSTRAINT FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
    );
